apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: <acr-name>.azurecr.io/node-app:latest
        ports:
        - containerPort: 8082
        env:
        - name: MYSQL_HOST
          value: "mysql-db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "Test1234"
        - name: MYSQL_DATABASE
          value: "HelloWorldPOC"
