name: CI/CD for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: alexlopesacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t alexlopesacr.azurecr.io/node-app:latest .
          docker push alexlopesacr.azurecr.io/node-app:latest

      - name: Set up Azure CLI
        uses: azure/azure-cli-action@v1.0.0

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group Rg_nodejs --name aks-cluster

      - name: Deploy to AKS
        run: |
          kubectl apply -f kubernetes/mysql-deployment.yml
          kubectl apply -f kubernetes/mysql-service.yml
          kubectl apply -f kubernetes/node-app-deployment.yml
          kubectl apply -f kubernetes/node-app-service.yml
